name: Deploy to Railway

on:
  push:
    branches: [react-query]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install pnpm and serve
        run: npm install -g pnpm serve
        
      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Install Railway
        run: npm install -g @railway/cli

      - name: Deploy
        run: railway up --service client-dashboard
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
